apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    project: k8s-demo
    app: angular
    type: ui
spec:
  type: NodePort
  ports:
    -
      name: ui
      port: 80
      nodePort: 30000
  selector:
    project: k8s-demo
    app: angular
    type: ui

