apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    project: k8s-demo
    app: nodejs
    type: microservice
spec:
  type: ClusterIP
  ports:
    -
      name: nodejs-api
      port: 3000
  selector:
    project: k8s-demo
    app: nodejs
    type: microservice