apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    project: k8s-demo
    app: redis
    type: db
spec:
  type: ClusterIP
  ports:
    -
      name: redis
      port: 6379
  selector:
    project: k8s-demo
    app: redis
    type: db

