apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    project: k8s-demo
    app: springboot
    type: microservice

spec:
  template:
    metadata:
      name: angular-app-pod
      labels:
        project: k8s-demo
        app: springboot
        type: microservice
    spec:
      containers:
        - name: springboot-app
          image: sriram5795/docker-demo-springboot
          ports:
          - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      project: k8s-demo
      app: springboot
      type: microservice