apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    project: k8s-demo
    app: springboot
    type: microservice
spec:
  type: ClusterIP
  ports:
    -
      name: springboot-api
      port: 8080
  selector:
    project: k8s-demo
    app: springboot
    type: microservice

