apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    project: k8s-demo
    app: nodejs
    type: microservice
spec:
  type: NodePort
  ports:
    -
      name: api
      port: 3000
      nodePort: 30081
  selector:
    project: k8s-demo
    app: nodejs
    type: microservice

